const categoryApi = "https://www.themealdb.com/api/json/v1/1/categories.php";
const ingredientFood =
    "https://www.themealdb.com/api/json/v1/1/list.php?i=list";
const mealsApi =
    "https://www.themealdb.com/api/json/v1/1/filter.php?i=chicken_breast";
const seafoodApi =
    "https://www.themealdb.com/api/json/v1/1/filter.php?c=Seafood";
const canadianFood =
    "https://www.themealdb.com/api/json/v1/1/filter.php?a=Canadian";
